FROM nginx:alpine

# Copy the Nginx config
COPY webapp/default.conf /etc/nginx/conf.d/default.conf

# Copy the BUILT files from the previous stage
# Notice we copy from "--from=build" instead of the local file system
COPY --from=build /app/mobile/build/web /usr/share/nginx/html